//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyApplicationFault", Namespace="http://schemas.datacontract.org/2004/07/cms.Service")]
    [System.SerializableAttribute()]
    public partial class MyApplicationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IClient")]
    public interface IClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/GetGridpage", ReplyAction="http://tempuri.org/IClient/GetGridpageResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(cms.ServiceReference1.MyApplicationFault), Action="http://tempuri.org/IClient/GetGridpageMyApplicationFaultFault", Name="MyApplicationFault", Namespace="http://schemas.datacontract.org/2004/07/cms.Service")]
        string GetGridpage(string application, string link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/GetGridpageJson", ReplyAction="http://tempuri.org/IClient/GetGridpageJsonResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(cms.ServiceReference1.MyApplicationFault), Action="http://tempuri.org/IClient/GetGridpageJsonMyApplicationFaultFault", Name="MyApplicationFault", Namespace="http://schemas.datacontract.org/2004/07/cms.Service")]
        string GetGridpageJson(string application, string link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/Echo", ReplyAction="http://tempuri.org/IClient/EchoResponse")]
        string Echo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/Ok", ReplyAction="http://tempuri.org/IClient/OkResponse")]
        string Ok();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/Fail", ReplyAction="http://tempuri.org/IClient/FailResponse")]
        string Fail();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientChannel : cms.ServiceReference1.IClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientClient : System.ServiceModel.ClientBase<cms.ServiceReference1.IClient>, cms.ServiceReference1.IClient {
        
        public ClientClient() {
        }
        
        public ClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetGridpage(string application, string link) {
            return base.Channel.GetGridpage(application, link);
        }
        
        public string GetGridpageJson(string application, string link) {
            return base.Channel.GetGridpageJson(application, link);
        }
        
        public string Echo() {
            return base.Channel.Echo();
        }
        
        public string Ok() {
            return base.Channel.Ok();
        }
        
        public string Fail() {
            return base.Channel.Fail();
        }
    }
}
