//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cms.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetGridpageRq", Namespace="http://schemas.datacontract.org/2004/07/cms.Service")]
    [System.SerializableAttribute()]
    public partial class GetGridpageRq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IClient")]
    public interface IClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/GetGridpage", ReplyAction="http://tempuri.org/IClient/GetGridpageResponse")]
        cms.data.Dtos.GridPageDto GetGridpage(cms.ServiceReference1.GetGridpageRq rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/GetGridpageJson", ReplyAction="http://tempuri.org/IClient/GetGridpageJsonResponse")]
        cms.data.Dtos.GridPageDto GetGridpageJson(cms.ServiceReference1.GetGridpageRq rq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/EchoJson", ReplyAction="http://tempuri.org/IClient/EchoJsonResponse")]
        string EchoJson(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClient/Echo", ReplyAction="http://tempuri.org/IClient/EchoResponse")]
        string Echo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientChannel : cms.ServiceReference1.IClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientClient : System.ServiceModel.ClientBase<cms.ServiceReference1.IClient>, cms.ServiceReference1.IClient {
        
        public ClientClient() {
        }
        
        public ClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public cms.data.Dtos.GridPageDto GetGridpage(cms.ServiceReference1.GetGridpageRq rq) {
            return base.Channel.GetGridpage(rq);
        }
        
        public cms.data.Dtos.GridPageDto GetGridpageJson(cms.ServiceReference1.GetGridpageRq rq) {
            return base.Channel.GetGridpageJson(rq);
        }
        
        public string EchoJson(string message) {
            return base.Channel.EchoJson(message);
        }
        
        public string Echo() {
            return base.Channel.Echo();
        }
    }
}
