// Generated by CoffeeScript 1.3.3

/*
@reference ../showdown.js
@reference ../jquery-1.7.2.js
@reference ../angular.js
*/


(function() {
  var reference;

  reference = function($scope, $http, appSettings) {
    $scope.grids = [];
    $scope.app = appSettings;
    $scope.Link = $scope.gridelement.Resources[0].Value;
    console.log($scope.gridelement, "sdsd ref");
    return 1;
  };

  window.reference = reference;

}).call(this);
