// Generated by CoffeeScript 1.3.3

/*
@reference ../showdown.js
@reference ../jquery-1.7.2.js
@reference ../angular.js
*/


(function() {
  var text;

  text = function($scope, $http) {
    text.$inject = ["$scope", "$http"];
    $scope.xxx = "xxxx";
    return 1;
  };

  window.text = text;

}).call(this);
