// Generated by CoffeeScript 1.3.3

/*
@reference ../showdown.js
@reference ../jquery-1.7.2.js
@reference ../angular.js
*/


(function() {
  var text;

  text = function($scope, $http) {
    return text.$inject = ["$scope", "$http"];
  };

  window.text = text;

}).call(this);
